"""empty message

Revision ID: 1222155ccf0d
Revises: 63aadd706459
Create Date: 2020-10-12 08:22:42.894621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1222155ccf0d"
down_revision = "63aadd706459"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meme_template", sa.Column("username", sa.String(length=4096), nullable=True)
    )
    op.drop_column("meme_template", "user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meme_template",
        sa.Column(
            "user_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("meme_template", "username")
    # ### end Alembic commands ###
