"""empty message

Revision ID: 63aadd706459
Revises: 51c3f4fa4162
Create Date: 2020-10-10 06:11:27.119264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "63aadd706459"
down_revision = "51c3f4fa4162"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=50), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("password", sa.String(length=80), nullable=True),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    op.add_column("meme_template", sa.Column("posted", sa.DateTime(), nullable=True))
    op.add_column("meme_template", sa.Column("user_id", sa.Integer(), nullable=True))
    op.alter_column(
        "meme_template",
        "title",
        existing_type=mysql.VARCHAR(length=4096),
        nullable=False,
    )
    op.alter_column(
        "meme_template", "url", existing_type=mysql.VARCHAR(length=4096), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "meme_template", "url", existing_type=mysql.VARCHAR(length=4096), nullable=True
    )
    op.alter_column(
        "meme_template",
        "title",
        existing_type=mysql.VARCHAR(length=4096),
        nullable=True,
    )
    op.drop_column("meme_template", "user_id")
    op.drop_column("meme_template", "posted")
    op.drop_table("user")
    # ### end Alembic commands ###
