"""empty message

Revision ID: a56e6ad0efa9
Revises: ce8f2834f11a
Create Date: 2020-10-09 11:18:13.360052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56e6ad0efa9'
down_revision = 'ce8f2834f11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme_template', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meme_template', 'posted')
    # ### end Alembic commands ###
