"""empty message

Revision ID: eca8ddca17c7
Revises: 1222155ccf0d
Create Date: 2020-10-14 15:20:56.624754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eca8ddca17c7"
down_revision = "1222155ccf0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meme_template", sa.Column("approved", sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, "user", ["username"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("meme_template", "approved")
    # ### end Alembic commands ###
