"""empty message

Revision ID: fd4b76fc3b0f
Revises: 
Create Date: 2020-10-10 06:09:27.415438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd4b76fc3b0f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meme_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=4096), nullable=False),
        sa.Column("description", sa.String(length=4096), nullable=True),
        sa.Column("url", sa.String(length=4096), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("posted", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.String(length=50), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("password", sa.String(length=80), nullable=True),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("meme_template")
    # ### end Alembic commands ###
